Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -9,6 +9,8 @@ trigger:
 pool:
   vmImage: 'ubuntu-latest'
 
+container: 
+
 variables:
   GOBIN:  '$(GOPATH)/bin' # Go binaries path
   GOROOT: '/usr/local/go' # Go installation path
@@ -38,18 +40,37 @@ steps:
 
 - script: |
     go get -u golang.org/x/lint/golint
-    golint $(find . -type f -name '*.go' -not -path "./vendor/*")
+    golint $(find . -type f -name '*.go' -not -path "./vendor/*") > /tmp/lint.out
+    cat /tmp/lint.out 
+    if [ -s /tmp/lint.out ]; then
+        echo -e "\e[101;97m golint FAILED \e[0m"``
+        exit 1
+    else
+        echo -e "\e[42;97m golint SUCCEEDED \e[0m"
+    fi
   workingDirectory: '$(modulePath)'
   displayName: 'Go lint'
 
 - script: |
-    go vet -v ./...
+    if go vet -v ./...; then
+        echo -e "\e[42;97m govet SUCCEEDED \e[0m"
+    else
+        echo -e "\e[101;97m govet FAILED \e[0m"``
+        exit 1
+    fi
   workingDirectory: '$(modulePath)'
   displayName: 'Go vet'
 
 - script: |
     go version
-    go install -v ./cmd/appgw-ingress
+    echo -e "\e[44;97m Compiling ... \e[0m"
+    if  go install -v ./cmd/appgw-ingress; then
+        chmod -R 777 bin
+        echo -e "\e[42;97m Build SUCCEEDED \e[0m"
+    else
+        echo -e "\e[101;97m Build FAILED \e[0m"
+        exit 1
+    fi
   workingDirectory: '$(modulePath)'
   displayName: 'Get dependencies and build'
   
